version: "3.7"
services:
  traefik:
    image: traefik:2.8.8
    container_name: traefik
    restart: always
    command:
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--log.level=warning"

      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"

      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
